security:
    password_hashers:
        App\Entity\Youssef:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Youssef
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: form_login # This ensures Symfony redirects unauthenticated users to /login

            form_login:
                login_path: login
                check_path: login
                default_target_path: /

            custom_authenticator: App\Security\AppAuthenticator

            logout:
                path: logout
                target: /

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 7 days
                path: /
                # Uncomment the following line if you want to always enable it
                # always_remember_me: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/menu, roles: ROLE_ADMIN }
        - { path: ^/reservation, roles: ROLE_ADMIN }
        - { path: ^/order, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            App\Entity\Youssef:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

